title: Sony Research Inc.
description: ""
baseurl: 
github_url: https://sonyresearch.github.io/multi_bias_amp

markdown: kramdown
kramdown:
    math_engine: katex

plugins:
  - jekyll/scholar
  - jekyll-katex

scholar:
  style: assets/csl/ieee-with-url.csl

source: ./
destination: ./_site

sass:
  sass_dir: assets/scss
  style: compressed