# Site settings
title: Sony AI
description: ""
baseurl:

# Build settings
markdown: kramdown
kramdown:
    math_engine: katex

plugins:
  - bourbon
  - neat
  - jekyll-feed
  - jekyll-paginate
  - jekyll-scholar
  - jekyll-katex

scholar:
  style: assets/csl/ieee-with-url.csl

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed
